name: cortex_ai_gallery
description: "An intelligent AI-powered photo gallery."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Packages
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  dio: ^5.4.3+1
  provider: ^6.1.2

  # UI & Widgets
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.1 # ADD THIS PACKAGE
  photo_view: ^0.15.0
  video_player: ^2.8.6

  # File System & Utilities
  path_provider: ^2.1.3
  file_picker: ^8.0.3
  watcher: ^1.1.0
  crypto: ^3.0.3
  shared_preferences: ^2.2.3

  # Code Generation Support
  json_annotation: ^4.9.0
  path: any
  gallery_saver_plus: ^3.2.9
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.0

  # Code Generators
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  # isar_generator has been removed

  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true