// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEhUb_Dpbzez0UWf6pPqlLaxuz3pjcsew',
    appId: '1:323836242613:web:495a341d2f1617ecb02cfc',
    messagingSenderId: '323836242613',
    projectId: 'cortex-ai-gallery-6d295',
    authDomain: 'cortex-ai-gallery-6d295.firebaseapp.com',
    storageBucket: 'cortex-ai-gallery-6d295.firebasestorage.app',
    measurementId: 'G-TN9VRZGTYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRobjmNHD545GTJgcLAV6Qk_RX74-tATs',
    appId: '1:323836242613:android:1ea0b3a7ac60e4aeb02cfc',
    messagingSenderId: '323836242613',
    projectId: 'cortex-ai-gallery-6d295',
    storageBucket: 'cortex-ai-gallery-6d295.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvTBBzWoJ08xsRcgQBy0LCSj_Dia-sRdA',
    appId: '1:323836242613:ios:2b44fd179c251bb5b02cfc',
    messagingSenderId: '323836242613',
    projectId: 'cortex-ai-gallery-6d295',
    storageBucket: 'cortex-ai-gallery-6d295.firebasestorage.app',
    iosBundleId: 'com.example.cortexAiGallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvTBBzWoJ08xsRcgQBy0LCSj_Dia-sRdA',
    appId: '1:323836242613:ios:2b44fd179c251bb5b02cfc',
    messagingSenderId: '323836242613',
    projectId: 'cortex-ai-gallery-6d295',
    storageBucket: 'cortex-ai-gallery-6d295.firebasestorage.app',
    iosBundleId: 'com.example.cortexAiGallery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEhUb_Dpbzez0UWf6pPqlLaxuz3pjcsew',
    appId: '1:323836242613:web:d5f3f0be179ab531b02cfc',
    messagingSenderId: '323836242613',
    projectId: 'cortex-ai-gallery-6d295',
    authDomain: 'cortex-ai-gallery-6d295.firebaseapp.com',
    storageBucket: 'cortex-ai-gallery-6d295.firebasestorage.app',
    measurementId: 'G-JR4MC07S56',
  );
}
